// examples/04-polyglot/apps/pricing/src/Root.vue
<script setup lang="ts">
defineProps<{ subpath?: string; basePath?: string; params?: Record<string, string> }>();
</script>

<template>
  <section class="jorvel-remote">
    <h1>pricing <small>(Vue 3 remote)</small></h1>
    <p>Sub-path: <code>{{ subpath }}</code></p>
    <p>This remote is mounted by the host through <code>@jorvel/mount</code>.</p>
  </section>
</template>

// examples/04-polyglot/apps/docs-site/src/Root.svelte
<script lang="ts">
  let { subpath = '/', basePath = '/', params = {} }:
    { subpath?: string; basePath?: string; params?: Record<string, string> } = $props();
</script>

<section class="jorvel-remote">
  <h1>docs-site <small>(Svelte 5 remote)</small></h1>
  <p>Sub-path: <code>{subpath}</code></p>
  <p>This remote is mounted by the host through <code>@jorvel/mount</code>.</p>
</section>
